import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import {Navbar, Footer} from '@/components'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Metaversus',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <head>
                <link rel='preconnect' href='https://stijndv.com' />
                <link rel='stylesheet' href='https://stijndv.com/fonts/Eudoxus-Sans.css' />
            </head>
            <body>
                <div className='bg-primary-black overflow-hidden'>
                <Navbar/>
                {children}
                <Footer/>
                </div>
            </body>
        </html>
    );
}
